INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);
INSERT INTO puestos(estado) VALUES(0);